version: '3.7'
services:
  mysql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=oioioi
      - POSTGRES_PASSWORD=qwerty1234